language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'node-bunyan-azure' ]; then cd .. && eval "mv $currentfolder node-bunyan-azure" && cd node-bunyan-azure; fi

